### ISSUE TITLE
Feedback on BSgenome.CneoformansVarGrubiiKN99.GenBank.1

### ISSUE THREAD

**Issue by hpages** [cmatKhan/BSgenome.CneoformansVarGrubiiKN99#1]
Hi @cmatKhan,

I'm taking a quick look at `BSgenome.CneoformansVarGrubiiKN99.GenBank.1` before we can add the package to Bioconductor.

As you already found out (and as documented in `?available.genomes`), the naming convention for BSgenome data packages is typically: `BSgenome.<organism>.<provider>.<assembly>`.

The `<provider>` part is never totally clear. Should it be GenBank, NCBI, FungiDB, or Washington University in St. Louis in this case? For assemblies that have been submitted to NCBI, the usage so far has been to use this as the provider. In any case, this should match the `provider:` field in the seed file.

The `<assembly>` part can be either the official assembly name displayed on [the NCBI landing page for this assembly](https://www.ncbi.nlm.nih.gov/assembly/GCA_002216725.1/) (`ASM221672v1`), or, if this is too ugly, the date of the assembly in `YYYYMMDD` form (`20170712`).

So this gives us `BSgenome.CneoformansVarGrubiiKN99.NCBI.ASM221672v1` or `BSgenome.CneoformansVarGrubiiKN99.NCBI.20170712`. Maybe the latter is a little bit less ugly than the former?

Note that, according to the NCBI landing page for this assembly, the organism name is "Cryptococcus neoformans var. grubii", so, in theory, something like `CneoformansVarGrubii` should be used for the `<organism>` part of the package name. Is the strain (KN99) important here so you feel that it should be part of the package name? In any case, this needs to remain consistent with the `organism:`, `BSgenomeObjname:`, and `organism_biocview:` fields in the seed file.

Finally the `genome:` field in the seed file should be set to the official assembly name: `ASM221672v1`.

See [the seed file that was used for BSgenome.Gmellonella.NCBI.ASM364042v2](https://github.com/Bioconductor/BSgenome/blob/master/inst/extdata/GentlemanLab/BSgenome.Gmellonella.NCBI.ASM364042v2-seed) for a relevant example.

Thanks,
H.

**Comment by cmatKhan** [comment]
@hpages 

I just pushed corrections based on your feedback -- thank you for the help.

1. The confusion re: the source/<provider> is fixed -- all changed to NCBI.

2. I prefer the name `BSgenome.CneoformansVarGrubiiKN99.NCBI.ASM221672v1`. I think keeping the strain information is necessary in this case -- for example, I may make another BSGenome object for strain H99.

3. `genome:` is corrected.

4. Question: I'm not aware of a common name for this organism. Is that a required field? If no, might be better to just remove `common_name` in this case.

Chase

**Comment by hpages** [comment]
@cmatKhan

Sorry for the delay.

I believe that `common_name:` is currently a required field. Maybe you can try to set it to NA?

One last thing: please use `Cryptococcus_neoformans_var_grubii_KN99` in the `biocViews:` field.

Other than that, the package is good to go.

Thanks,
H.

**Comment by hpages** [comment]
@cmatKhan
 
Hi Chase, do you intend to follow up on this?

Best,
H.

**Comment by cmatKhan** [comment]
@hpages 
Yes! I apologize -- I let other projects distract me.

The updates from Jan 28 are complete.

**Comment by hpages** [comment]
Hi @cmatKhan,

All looks good. I just added **BSgenome.CneoformansVarGrubiiKN99.NCBI.ASM221672v1_1.0.0.tar.gz** to the Bioconductor 3.15 repos. Sorry for the delay.

The package should become available to BioC 3.15 users via `BiocManager::install()` in about 3 hours.

Best,
H.

**Comment by cmatKhan** [comment]
@hpages  No problem re: delay whatsoever -- I appreciate your help in getting this into the correct shape. This is the first time I've shared something on a public repository, and it has been a very good learning experience. Thank you!
